#include "commonhvll.h"
#include "stdlib.h"

void print_bytes(const uint8_t *s, size_t l) {
  for (size_t i = 0; i < l; i++) {
    printf("%i,", s[i]);
  }
}

void print_hashmap(hashMap *h, size_t len, size_t cap){
  printf("{(hashMapEntry[]){");
  for (size_t i = 0; i < cap; i++) {
    if(!h->ks[i].k_length){
      printf("{0");
      printf(", %lu},", h->ks[i].k_length);
      continue;
    }
    printf("{(uint8_t[]){");
    print_bytes(h->ks[i].k, h->ks[i].k_length);
    printf("}, %lu},", h->ks[i].k_length);
  }
  printf("},(void*[]){");
  for (size_t i = 0; i < cap; i++) {
    if(h->v[i]){
      printf("(void*)%lu, ", (size_t)h->v[i]);
      continue;
    }
    printf("0, ");
  }
  printf("}, %lu, %lu};\n", len, cap);
}


#define THMAPCAP 512

int main() {
  struct tkent *tk = malloc(sizeof(tkns));
  memcpy(tk, &tkns, sizeof(tkns));
  size_t largest_token_name;
  hashMap th = {.ks = calloc(THMAPCAP, sizeof(hashMapEntry)),
                  .v = calloc(THMAPCAP, sizeof(void *)),
                  .cap = THMAPCAP};
  for (size_t i = TKNFLOOR; i <= sizeof(tkns) / sizeof(struct tkent) - TKNFLOOR;
       i++) {
    hashMapInsert(&th, tkns[i].s.s, tkns[i].s.l, (void *)i);
  }
  printf("#pragma once\n#include \"commonhvll.h\"\n// generated by hagen.c\nconst hashMap tkhm = ");
  print_hashmap(&th, th.len, th.cap);
  hashMap symhm = {.ks = calloc(HASHMAP_DEFAULT_CAPACITY, sizeof(hashMapEntry)),
                  .v = calloc(HASHMAP_DEFAULT_CAPACITY, sizeof(void *)),
                  .cap = HASHMAP_DEFAULT_CAPACITY};
  printf("\n");
  for(size_t i = 0; i < sizeof(builtin_symbols) / sizeof(struct Symbol); i++){
    printf("");
    hashMapInsert(&symhm, builtin_symbols[i].sym_name.s, builtin_symbols[i].sym_name.l, (void*)(i));
  }
}