#include "commonhvll.h"
#include "stdlib.h"
#include <stdio.h>

void print_bytes(const uint8_t *s, size_t l) {
  for (size_t i = 0; i < l; i++) {
    printf("%i,", s[i]);
  }
}

void print_tokens_hashmap(hashMap *h) {
  printf("{(str[]){");
  for (size_t i = 0; i < h->cap; i++) {
    if (!h->ks[i].l) {
      printf("{0,0},");
      continue;
    }
    printf("{(uint8_t[]){");
    print_bytes(h->ks[i].s, h->ks[i].l);
    printf("},%lu},", h->ks[i].l);
  }
  printf("},(void*[]){");
  for (size_t i = 0; i < h->cap; i++) {
    if (h->v[i]) {
      printf("(void*)%lu,", (size_t)h->v[i]);
      continue;
    }
    printf("0,");
  }
  printf("},%lu,%lu};\n", h->len, h->cap);
}

void print_builtin_symbols_hashmap_with_sub_one(hashMap *h) {
  printf("{(str[]){");
  for (size_t i = 0; i < h->cap; i++) {
    if (!h->ks[i].s) {
      printf("{0,0},");
      continue;
    }
    printf("{(uint8_t[]){");
    print_bytes(h->ks[i].s, h->ks[i].l);
    printf("}, %lu}, ", h->ks[i].l);
  }
  printf("},(void*[]){");
  for (size_t i = 0; i < h->cap; i++) {
    if (h->v[i]) {
      printf("(void*)&builtin_symbols[%lu],", (size_t)h->v[i] - 1);
      continue;
    }
    printf("0,");
  }
  printf("}, %lu, %lu};\n", h->len, h->cap);
}

#define HMAPCAP 256

int main() {
  size_t largest_token_name;
  hashMap th = {.ks = calloc(HMAPCAP, sizeof(str)),
                .v = calloc(HMAPCAP, sizeof(void *)),
                .cap = HMAPCAP};
  for (size_t i = TKNFLOOR; i < (sizeof(tkns) / sizeof(struct tkent));
       i++) {
    hashMapInsert(&th, tkns[i].s.s, tkns[i].s.l, (void *)i);
  }
  printf("#pragma once\n#include \"commonhvll.h\"\n// generated by "
         "hagen.c\nconst hashMap tkhm = ");
  print_tokens_hashmap(&th);
  hashMap symhm = {.ks = calloc(HMAPCAP, sizeof(str)),
                   .v = calloc(HMAPCAP, sizeof(void *)),
                   .cap = HMAPCAP};
  for (size_t i = 0; i < sizeof(builtin_symbols) / sizeof(struct Symbol); i++) {
    hashMapInsert(&symhm, builtin_symbols[i].sym_name.s,
                  builtin_symbols[i].sym_name.l, (void *)(i + 1));
  }
  printf("const hashMap builtinsymhm = ");
  print_builtin_symbols_hashmap_with_sub_one(&symhm);
}